[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[hostname]
ssh_only = false
format = "[⟪$hostname⟫]($style) in "
disabled = false

[username]
format = "[$user]($style) on "
show_always = true

[directory]
truncation_length = 8

[env_var]
variable = "_CUSTOM_SHELL"
format="[\\(inside $env_value shell\\)](bold red) "
